language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ZcHHuqH+xEsa0rjsJ8tgVJbN04cpWHQ4MbSwXz9Cx9IrGFNloGFAIV6brbfSS6SuyjbjjtSYL9R1d0UdLTsTS6dQnlZwIg1csIi9w9BdNQ8Avb1G4RCMg0aObNAjh2amKpU205yVrpjmYJOJvsTLo0grMMDv1r04t82/vEMZ+wJnoZ441S0GaCKklWRNsdhaoVZSFlqJF8APqQ52cM/q6oq76XUah1WlIwWfd643BBkU8Zfqd7lgi/68EEC0NaOe99Bii1xAP6h/mI9ZHQqW1R4eCpFX7mkFacX8+sloscTCZBGO2fabJNPcquFXFqWyYu5KGGJWe8B8CWAi0MohKJna3lFAPANz26sJwDTEEeGlhUmeZzmmpctA5ywBtsBp5mox6ace4w3RUWbABccOKD5pl9D5V996YWGUXOTh1UcrIOZDh5Px+kCihZw/JqUem3pFULA+hPxU8r32omU1Mgl6lIRl7kjuVvbat9crc7zsInpeLIzGqgEL01b8nVS934VucB7KPzDQT8zFVEcOCbIhMj/0IuHZg2TwLUrLkMfiM64sToZ1RJep2RhEQN8lRmukN5XJLUBf1FooLi1JdGnIT95jgeh7k7FmpYShFUK+3GPLVpluzWbCC0hYsdDsx0mDCqBY/AUXkbjwugzzwi1nxj0o1fPwkCX6TUEb5+E=
  app: trabalhotopico121
  on:
    repo: ThiagoAlbertino/trabalhotopico121
